name: flutter_socket_plugin_fix
description: FlutterSocket is a practical cross-platform socket plugin,supports both iOS and Android.
version: 1.0.2
homepage: https://github.com/Asutos/flutter_socket_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cn.waitwalker.flutter_socket_plugin
    pluginClass: FlutterSocketPlugin