name: flutter_socket_plugin
description: FlutterSocket is a practical cross-platform socket plugin,supports both iOS and Android. At present, it has realized the basic functions of client side:create, connect, send, receive, disconnect, heartbeat and so on.
version: 0.0.1
author: waitwalker <rohit@infitio.com>
homepage: https://github.com/waitwalker/flutter_socket_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cn.waitwalker.flutter_socket_plugin
    pluginClass: FlutterSocketPlugin